name: Uno Game CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10", "3.12"]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Lint with Ruff
      run: |
        # Ruff is already installed via pip install .[dev]
        ruff check uno_game/

    - name: Format check with Black
      run: |
        # Black is already installed via pip install .[dev]
        black --check uno_game/

    - name: Type check with Mypy
      run: |
        # Mypy is already installed via pip install .[dev]
        mypy uno_game/

    - name: Run tests with Pytest
      run: |
        # Pytest is already installed via pip install .[dev]
        pytest
